services:
  backend:
    build:
      context: ../backend
      dockerfile: ../deployment/Dockerfile.backend
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ../frontend
      dockerfile: ../deployment/Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend