// Package swagger provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package swagger

// CalcResult defines model for CalcResult.
type CalcResult struct {
	ItemsOrdered   *int            `json:"itemsOrdered,omitempty"`
	PacksUsed      *map[string]int `json:"packsUsed,omitempty"`
	TotalItemsUsed *int            `json:"totalItemsUsed,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// PackSizesPayload defines model for PackSizesPayload.
type PackSizesPayload struct {
	// PackSizes An array of positive integers representing pack sizes. Zero or negative values are not allowed.
	PackSizes []int `json:"pack_sizes"`
}

// GetV1CalcParams defines parameters for GetV1Calc.
type GetV1CalcParams struct {
	// Items Number of items ordered.
	Items int `form:"items" json:"items"`
}

// PutV1PackSizesJSONRequestBody defines body for PutV1PackSizes for application/json ContentType.
type PutV1PackSizesJSONRequestBody = PackSizesPayload
